Create failing scenario
Test failure:
```
❯ npm test

 FAIL  ./index.test.js
  ✕ spyOn export from (2 ms)

  ● spyOn export from

    TypeError: Cannot redefine property: log
        at Function.defineProperty (<anonymous>)

      2 |
      3 | test('spyOn export from', () => {
    > 4 |   const log = jest.spyOn(Lib, 'log')
        |                    ^
      5 |   console.log('uncalled')
      6 | })
      7 |

      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:826:16)
      at Object.<anonymous> (index.test.js:4:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.994 s, estimated 1 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Transpiled test code:
```
❯ npx babel index.test.js
"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

var Lib = _interopRequireWildcard(require("./lib"));

function _getRequireWildcardCache() { if (typeof WeakMap !== "function") return null; var cache = new WeakMap(); _getRequireWildcardCache = function _getRequireWildcardCache() { return cache; }; return cache; }

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } if (obj === null || _typeof(obj) !== "object" && typeof obj !== "function") { return { "default": obj }; } var cache = _getRequireWildcardCache(); if (cache && cache.has(obj)) { return cache.get(obj); } var newObj = {}; var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null; if (desc && (desc.get || desc.set)) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } newObj["default"] = obj; if (cache) { cache.set(obj, newObj); } return newObj; }

test('spyOn export from', function () {
  var log = jest.spyOn(Lib, 'log');
  console.log('uncalled');
});
```